### ISSUE TITLE
Extensions support in X509 matching

### ISSUE THREAD

**Issue by MikaelSmith** [square/rails-auth#52]
This is great, kind of like https://github.com/puppetlabs/trapperkeeper-authorization for Rack.

A feature I'd like to see added is extracting extensions - such as subjectAltName - from the certificate in `Rails::Auth::X509::Certificate` so we can match against them in an ACL.

**Comment by nerdrew** [comment]
You should be able to access the raw `OpenSSL::X509::Certificate` via `#certificate`. You can read extensions, etc. from that.

**Comment by MikaelSmith** [comment]
Ok, thanks for the pointer.
