### ISSUE TITLE
Consider using YAML.safe_load instead of YAML.load

### ISSUE THREAD

**Issue by mbyczkowski** [square/rails-auth#60]
When I was upgrading the version of rubocop in #53, I've temporarily disabled a cop in https://github.com/square/rails-auth/blob/803225fed67091673a45439c915aed9abfc6faaf/lib/rails/auth/acl.rb#L21-L24, because I wasn't 100% sure on the implications of this change. Nonetheless, this should be something that someone should look at.

**Comment by mbyczkowski** [comment]
I think `YAML.safe_load(yaml, [], [], true)` would probably work here.  According to the [documentation](https://docs.ruby-lang.org/en/2.5.0/Psych.html#method-c-safe_load) this particular invocation would allow for aliases in YAML files (the default for `safe_load` is to raise an exception in such a case).

**Comment by nerdrew** [comment]
Fixed in https://github.com/square/rails-auth/pull/75
