### ISSUE TITLE
Rails::Auth is incompatible with Ruby 3.1

### ISSUE THREAD

**Issue by petergoldstein** [square/rails-auth#73]
Because of an underlying issue with the certificate_authority gem, Rails::Auth currently can't be used with Ruby 3.1.

The OpenSSL::Config was made immutable in Ruby 3.1.  The certificate_authority gem attempts to mutate an instance of that class, which fails in Ruby 3.1.

I've submitted a PR against certificate_authority to help resolve this issue - https://github.com/cchandler/certificate_authority/pull/60 .  This fix (or an alternate) will need to be merged and a new version released to enable Ruby 3.1 for Rails::Auth.

**Comment by petergoldstein** [comment]
I've put up a PR on my fork that, when there's a certificate_authority update, will address the remaining Ruby 3.1 issues (basically Rubocop) - https://github.com/petergoldstein/rails-auth/pull/1

**Comment by nerdrew** [comment]
I think this is resolved now b/c the `certificate_authority` PR was merged.
